Adding 2-environments  yaml

diff --git a/azure-pipelines/environments_stage/environments.yaml b/azure-pipelines/environments_stage/environments.yaml
--- a/azure-pipelines/environments_stage/environments.yaml
+++ b/azure-pipelines/environments_stage/environments.yaml
@@ -1,35 +1,64 @@
 stages:
-- stage: org
-  displayName: 'env terraform'
+- stage: environments_stage
+  displayName: 'environments terraform'
 
   jobs:
-  - job: SetupJob
-    displayName: 'Setup Job'
+  - job: setupworkspace
+    displayName: 'Setup workspace'
     steps:
+    - download: current
+      artifact: OrgArtifact
+      displayName: 'Download Org Artifact'
+    - template: ../templates/securefile-template.yaml
     - script: |
-        ./Impersonate.sh $var1 $var2
-      displayName: 'Impersonate SA'
+        echo "Cleaning the current environment..."
+        rm -rf $(Build.SourcesDirectory)/*
 
-  - job: DeployDev
-    displayName: 'Deploy development'
-    dependsOn: SetupJob
-    steps:
-    - script: |
-        ./DeployDev $var1 $var2
-      displayName: 'Plan Terraform'
+        echo "Moving downloaded artifacts to the source directory..."
+        mv $(Pipeline.Workspace)/OrgArtifact/* $(Build.SourcesDirectory)/
+        mv $(Pipeline.Workspace)/OrgArtifact/.* $(Build.SourcesDirectory)/ 2> /dev/null || true
 
-  - job: DeploynonProd
-    displayName: 'DeploynonProd'
-    dependsOn: DeployDev
-    steps:
-    - script: |
-        ./DeploynonProd.sh $var1 $var2
-      displayName: 'Deploy Non production'
+        echo "Current environment contents:"
+        ls -l $(Build.SourcesDirectory)/
+        echo "Checking if 1-org exists and listing contents:"
+        if [ -d "$(Build.SourcesDirectory)/1-org" ]; then
+          ls -l $(Build.SourcesDirectory)/1-org/
+        else
+          echo "1-org directory not found."
+        fi
+        echo "Whole env list from sources directory:"
+        echo "list 1-org"
+        ls -l 1-org/
 
-  - job: DeployProd
-    displayName: 'DeployProd'
-    dependsOn: DeploynonProd
-    steps:
-    - script: |
-        ./DeployProd.sh $var1 $var2
-      displayName: 'Apply Terraform'
+        ls -l $(Build.SourcesDirectory)/
+        echo "Terraform version :"
+        terraform version
+        echo "tf v1.6"
+        wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
+        unzip terraform_1.6.0_linux_amd64.zip
+        sudo mv terraform /usr/local/bin/
+        sudo chmod +x /usr/local/bin/terraform
+        echo "Terraform version :"
+        terraform version
+        echo "list 1-org"
+        ls -l 1-org/
+        echo "list hubandspoke"
+        ls -l 3-networks-hub-and-spoke/
+        echo "set exec permission"
+        chmod +x ./automation-scripts/1-org/1-org.sh
+        echo "Executing org.sh:"
+        echo "which sa is activated"
+        gcloud auth list
+        python3 ./fix_tfvars_symlinks.py .
+        gcloud auth activate-service-account sa-gcp-partners-test@sa-test-gcp.iam.gserviceaccount.com --key-file=$(googleCredentials.secureFilePath)
+        gcloud config set project sa-test-gcp
+        echo "which sa is activated"
+        gcloud auth list
+        export GOOGLE_APPLICATION_CREDENTIALS=$(googleCredentials.secureFilePath)
+        echo $GOOGLE_APPLICATION_CREDENTIALS
+        ./automation-scripts/2-environments/2-environments.sh
+      displayName: 'Replace and Confirm Environment'
+    - publish: $(System.DefaultWorkingDirectory)
+      artifact: EnvironmentsArtifact
+      displayName: 'Publish Environments Environment'
+
